export default [
  { id: 1, name: "ali hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 2, name: "ali ", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 3, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 4, name: "ali ", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 5, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 6, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 7, name: "ali ", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 8, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 9, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 10, name: "ali ", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 11, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 12, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 13, name: "ali ", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
  { id: 14, name: " hamadi", email: "ali@gmail.com", date: "11 sep 2011", delete: false },
]
